/*
********************************************************************************
[File]          : ELB_ISR.c
[Version]       :
[Processor]     : PIC24FJ256GB206
[Compiler]      : MPLABC30
[Description]   : Interrupt Service Routine for various peripherals to be written
                  in this file. The name of functions for interrupt service routine
                  can be found in Interrupt Vector Table section of the document
                  "MPLAB_C_Compiler_PIC24_dsPIC_UG_51284J.pdf" placed at
                  INSTALL LOCATION \mplabc30\v3.30c\docs
--------------------------------------------------------------------------------
[VERSION]	[DATE]   	[AUTHOR] 				CHANGES
********************************************************************************
*/

/*** MICROCHIP LIBRARY ***/
#include <p24fxxxx.h>
#include <p24FJ256GB206.h>
#include <pic24f_periph_features.h>
#include <timer.h>

/*** BRIGOSHA LIBRARY ***/
#include "Define.h"


U8 V_T23IntFlag_U8 = 0;

/*
--------------------------------------------------------------------------------------------------- 
[NAME]  	 : _T2Interrupt
[TYPE]		 : Interrupt service routine
[INPUT] 	 : None
[RETURN]	 : None
[DESCRIPTION]: This function Interrupts when the timer compare/Tick value has elapsed. Any multiple of 1 mSec
			   timer can be generated by specifying the value in SampleTime variable.
--------------------------------------------------------------------------------------------------- 
*/
void __attribute__ ((interrupt,no_auto_psv)) _T23Interrupt(void)
{ 	
 	T23_Clear_Intr_Status_Bit;
        V_T23IntFlag_U8 = 1;
 
}


