
//=================================================================================================
//
//	===============================================================================================
//	PRODUCT:			---------- AVIX - (ADVANCED VIRTUAL INTEGRATED EXECUTIVE) RTOS ------------
//	===============================================================================================
//
//	===============================================================================================
//	PRODUCT VERSION: 	5.0
//	COPYRIGHT:			AVIX-RT EMBEDDED SOLUTIONS
//	===============================================================================================
//
//	===============================================================================================
//	UNDER NO CIRCUMSTANCE MAY THE CONTENT OF THIS FILE BE CHANGED. ANY CHANGE OF THE DEFINITIONS IN
//	THIS FILE MAY  LEAD TO AVIX  NOT WORKING OR WORKING  IN A UNPREDICTABLE  MANNER.
//	===============================================================================================
//
//	SOFTWARE LICENSE AGREEMENT
//	--------------------------
//
//	THE  SOFTWARE  SUPPLIED  HEREWITH  AS  THE  CONTENT  OF  THIS FILE IS OWNED BY AVIX-RT EMBEDDED
//	SOLUTIONS  (THE "COMPANY"), AND IS PROTECTED  UNDER APPLICABLE  COPYRIGHT LAWS.  ALL RIGHTS ARE
//	RESERVED.  THE SOFTWARE IS SUPPLIED TO YOU (THE "CUSTOMER")  FOR USE  SOLELY AND EXCLUSIVELY AS
//	PART OF AND TOGETHER WITH PRODUCTS MANUFACTURED BY "COMPANY" AND LICENSED TO "CUSTOMER".
//
//	"COMPANY" LICENSES "CUSTOMER"  THE RIGHT TO USE  THIS FILE FOR THE  SOLE PURPOSE  OF DEVELOPING
//	APPLICATION SOFTWARE BASED ON ONE OF "COMPANIES" PRODUCTS AND FOR EXCLUSIVE USE ON A  SUPPORTED
//	MICROCONTROLLER.
//
//	UNDER NO CIRCUMSTANCE  MAY THE CONTENT OF  THIS FILE,  EITHER PARTIALLY  OR COMPLETE,  BE  MADE
//	PUBLIC, EITHER ELECTRONICALLY OR PRINTED.
//
//	ANY VIOLATION TO THE FOREGOING RESTRICTIONS  MAY SUBJECT THE USER  TO CRIMINAL SANCTIONS  UNDER
//	APPLICABLE LAWS, AS WELL AS TO CIVIL  LIABILITY FOR  THE BREACH  OF THE TERMS AND CONDITIONS OF
//	THIS LICENSE.
//
//	YOU SHOULD REFER TO THE LICENSE AGREEMENT  ACCOMPANYING THE  PRODUCT THIS  SOFTWARE IS  PART OF
//	FOR ADDITIONAL INFORMATION REGARDING YOUR RIGHTS AND OBLIGATIONS.
//
//	THE SOFTWARE  AND DOCUMENTATION  ARE PROVIDED  "AS IS"  WITHOUT  WARRANTY  OF ANY  KIND, EITHER
//	EXPRESS OR IMPLIED, INCLUDING WITHOUT  LIMITATION, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR
//	A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL "COMPANY" BE LIABLE FOR ANY
//	INCIDENTAL, SPECIAL,  INDIRECT OR  CONSEQUENTIAL DAMAGES,  LOST PROFITS  OR LOST  DATA, COST OF
//	PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY OR SERVICES, ANY CLAIMS BY THIRD PARTIES (INCLUDING
//	BUT NOT  LIMITED TO ANY DEFENSE  THEREOF),  ANY CLAIMS  FOR  INDEMNITY OR CONTRIBUTION,OR OTHER
//	SIMILAR COSTS, WHETHER ASSERTED ON THE BASIS OF  CONTRACT, TORT  (INCLUDING NEGLIGENCE), BREACH
//	OF WARRANTY, OR OTHERWISE.
//
//	COPYRIGHT (C) 2006-2012 AVIX-RT EMBEDDED SOLUTIONS.  ALL RIGHTS RESERVED.
//
//	===============================================================================================
//
//	THIS SOURCE FILE  IS DISTRIBUTED AS  PART OF AVIX.  IT MUST  BE COMPILED  IN  THE  USER PROJECT
//	ENVIRONMENT AND LINKED WITH THE USER SOURCE FILES AND THE AVIX LIBRARY TO FORM THE END PRODUCT.
//
// 	THE PURPOSE OF THIS FILE IS TO LINK THE SETTINGS FROM AVIXSystemSettings.h IN THE USER PRODUCT.
//
//	THIS  FILE SHOULD UNDER NO CIRCUMSTANCE BE MODIFIED AND ALWAYS BE USED AS IT IS RECEIVED IN THE 
//	DISTRIBUTION. ANY MOFIDICATION WILL CHANGE THE WORKINGS OF AVIX.
//
//	ALWAYS MAKE  SURE THE  VERSION NUMBER IN  THIS FILE  IS THE SAME AS  THE VERSION  NUMBER OF THE 
//	LIBRARY YOU ARE USING.  IF THE VERSIONS  OF THE TWO  DO NOT COMPLY THIS MIGHT LEAD TO NOT BEING
//	ABLE TO BUILD THE PRODUCT. SINCE A VERSION MISMATCH DOES NOT NECESERALLY LEAD TO NOT BEING ABLE
//	TO BUILD  THE PRODUCT, AS A  SAFEGUARD AVIX DOES DURING ITS STARTUP A CHECK WHETHER THE VERSION
//	NUMBER OF THIS FILE AND THE AVIX LIBRARY MATCH. 
//
//	===============================================================================================
//	-----------------------------------------------------------------------------------------------
//  --------------------- AVIX CONFIGURATION GENERATOR SECTION 1 (INCLUDE FILES) ------------------
//	-----------------------------------------------------------------------------------------------
//	------- THIS SECTION IS GENERATED BY THE AVIX DISTRIBUTION BUILD PROCESS, DO NOT CHANGE -------
//	-----------------------------------------------------------------------------------------------
// 	===============================================================================================
//
#include "stdio.h"
#include "limits.h"

//	===============================================================================================
//	THIS CONFIGURATION FILE BELONGS TO A FREE DEMO DISTRIBUTION PREBUILD FOR A SPECIFIC CONTROLLER.
//	FOR A FREE DEMO  DISTRIBUTION THIS SECTION  IS EMPTY  SINCE NO  BUILD TIME SELECTION OF TYPE OF
//	CONTROLLER OR OTHER CONFIGURATION SETTING IS POSSIBLE.
//	===============================================================================================






//	===============================================================================================
//	-----------------------------------------------------------------------------------------------
//  --------------------- AVIX CONFIGURATION GENERATOR SECTION 2 (MACRO'S) ------------------------
//	-----------------------------------------------------------------------------------------------
//	------- THIS SECTION IS GENERATED BY THE AVIX DISTRIBUTION BUILD PROCESS, DO NOT CHANGE -------
//	-----------------------------------------------------------------------------------------------
// 	===============================================================================================
//
//	===============================================================================================
//	THIS CONFIGURATION FILE BELONGS TO A FREE DEMO DISTRIBUTION PREBUILD FOR A SPECIFIC CONTROLLER.
//	FOR A FREE DEMO  DISTRIBUTION THIS SECTION  IS EMPTY  SINCE NO  BUILD TIME SELECTION OF TYPE OF
//	CONTROLLER OR OTHER CONFIGURATION SETTING IS POSSIBLE.
//	===============================================================================================





//	===============================================================================================
//	-----------------------------------------------------------------------------------------------
//  --------------------- AVIX CONFIGURATION GENERATOR SECTION 3 (CONFIGURATION VARIABLES) --------
//	-----------------------------------------------------------------------------------------------
//	------- THIS SECTION IS GENERATED BY THE AVIX DISTRIBUTION BUILD PROCESS, DO NOT CHANGE -------
//	-----------------------------------------------------------------------------------------------
// 	===============================================================================================
//
//	===============================================================================================
//	THIS CONFIGURATION FILE BELONGS TO A FREE DEMO DISTRIBUTION PREBUILD FOR A SPECIFIC CONTROLLER.
//	FOR A FREE DEMO  DISTRIBUTION THIS SECTION  IS EMPTY  SINCE NO  BUILD TIME SELECTION OF TYPE OF
//	CONTROLLER OR OTHER CONFIGURATION SETTING IS POSSIBLE.
//	===============================================================================================





//
//	===============================================================================================
//	-----------------------------------------------------------------------------------------------
//  --------------------- AVIX CONFIGURATION GENERATOR SECTION 4 (CONFIGURATION HELP FUNCTIONS) ---
//	-----------------------------------------------------------------------------------------------
//	------- THIS SECTION IS GENERATED BY THE AVIX DISTRIBUTION BUILD PROCESS, DO NOT CHANGE -------
//	-----------------------------------------------------------------------------------------------
// 	===============================================================================================
//
//	===============================================================================================
//	THIS CONFIGURATION FILE BELONGS TO A FREE DEMO DISTRIBUTION PREBUILD FOR A SPECIFIC CONTROLLER.
//	FOR A FREE DEMO  DISTRIBUTION THIS SECTION  IS EMPTY  SINCE NO  BUILD TIME SELECTION OF TYPE OF
//	CONTROLLER OR OTHER CONFIGURATION SETTING IS POSSIBLE.
//	===============================================================================================





//
//	===============================================================================================
//	-----------------------------------------------------------------------------------------------
//  --------------------- AVIX CONFIGURATION GENERATOR SECTION 5 (PLATFORM ADAPTER FUNCTIONS) -----
//	-----------------------------------------------------------------------------------------------
//	------- THIS SECTION IS GENERATED BY THE AVIX DISTRIBUTION BUILD PROCESS, DO NOT CHANGE -------
//	-----------------------------------------------------------------------------------------------
// 	===============================================================================================
//
//	===============================================================================================
//	THIS CONFIGURATION FILE BELONGS TO A FREE DEMO DISTRIBUTION PREBUILD FOR A SPECIFIC CONTROLLER.
//	FOR A FREE DEMO  DISTRIBUTION THIS SECTION  IS EMPTY  SINCE NO  BUILD TIME SELECTION OF TYPE OF
//	CONTROLLER OR OTHER CONFIGURATION SETTING IS POSSIBLE.
//	===============================================================================================

/* End of file */

